apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: machinehealths.eranco74.redhat
spec:
  group: eranco74.redhat
  names:
    kind: MachineHealth
    listKind: MachineHealthList
    plural: machinehealths
    singular: machinehealth
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: MachineHealth is the Schema for the machinehealths API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MachineHealthSpec defines the desired state of MachineHealth
          properties:
            interval:
              type: integer
            ip:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
            machinehealth:
              type: string
            port:
              type: string
          required:
          - interval
          - ip
          - machinehealth
          - port
          type: object
        status:
          description: MachineHealthStatus defines the observed state of MachineHealth
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
