apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      name: inventory
  template:
    metadata:
      labels:
        name: inventory
    spec:
      serviceAccountName: inventory
      containers:
        - name: inventory
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - inventory
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "inventory"
