kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: inventory-pod
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: default
    # Reference to upper's `metadata.namespace`
    namespace: default
roleRef:
  kind: Role
  name: inventory
  apiGroup: rbac.authorization.k8s.io
